faq: fix lỗi hiển thị bài viết chưa duyệt và đã duyệt ở ngoài site của thành viên
nukeviet/module-faq pull request #14
Opened 2017-04-14 08:47 UTC by ngocphan123

2017-04-14 09:48 UTC, hoaquynhtim99 requested changes

2017-04-14 09:48 UTC, hoaquynhtim99 commented on modules/faq/funcs/list.php
> +$sql .= ' WHERE userid ='.$user_info['userid'] ;
```php
userid ='.$user_info['userid'] ;
```
Cái này cần chú ý chuẩn PSR-2: http://www.php-fig.org/psr/psr-2/ trước sau dấu `.` cần space và trước `;` không được có space.

Tương tự cho đoạn bên dưới

2017-04-14 09:57 UTC, ngocphan123 commented
Vâng a em sửa lại ạ


2017-04-14 16:48 GMT+07:00 Tan Dung Phan <notifications@github.com>:

> *@hoaquynhtim99* requested changes on this pull request.
> ------------------------------
>
> In modules/faq/funcs/list.php
> <https://github.com/nukeviet/module-faq/pull/14#discussion_r111555024>:
>
> > @@ -39,6 +39,7 @@
>  //List bài viết đã được duyệt
>  $sql = 'SELECT SQL_CALC_FOUND_ROWS * FROM ' . NV_PREFIXLANG . '_' . $module_data . '';
>  $base_url = NV_BASE_SITEURL . 'index.php?' . NV_LANG_VARIABLE . '=' . NV_LANG_DATA . '&' . NV_NAME_VARIABLE . '=' . $module_name . '&' . NV_OP_VARIABLE . '=list';
> +$sql .= ' WHERE userid ='.$user_info['userid'] ;
>
> userid ='.$user_info['userid'] ;
>
> Cái này cần chú ý chuẩn PSR-2: http://www.php-fig.org/psr/psr-2/ trước
> sau dấu . cần space và trước ; không được có space.
>
> Tương tự cho đoạn bên dưới
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nukeviet/module-faq/pull/14#pullrequestreview-32809476>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANklAZ_VFlkUW3YbjUZYhpHwfjLyt5T0ks5rv0EFgaJpZM4M9kv1>
> .
>

2017-04-25 02:39 UTC, hoaquynhtim99 approved these changes

2017-04-25 02:39 UTC, merged